export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


//Usuário
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_UPDATED_SUCCESS = 'REGISTER_UPDATED_SUCCESS';
export const REGISTER_CREATED_SUCCESS = 'REGISTER_CREATED_SUCCESS';

//TRANSAÇOES
export const REGISTER_TRANSACTION_REQUEST = 'REGISTER_TRANSACTION_REQUEST';
export const REGISTER_TRANSACTION_FAILURE = 'REGISTER_TRANSACTION_FAILURE';
export const REGISTER_TRANSACTION_SUCCESS = 'REGISTER_TRANSACTION_SUCCESS';
export const REGISTER_TRANSACTION_UPDATED_SUCCESS = 'REGISTER_TRANSACTION_UPDATED_SUCCESS';


//FOTOS
export const REGISTER_FOTO_REQUEST = 'REGISTER_FOTO_REQUEST';
export const REGISTER_FOTO_SUCCESS = 'REGISTER_FOTO_SUCCESS';
export const REGISTER_FOTO_FAILURE = 'REGISTER_FOTO_FAILURE';
export const REGISTER_FOTO_UPDATE_SUcCESS = 'REGISTER_FOTO_UPDATE_SUcCESS';


export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
