import Head from 'next/head'
import Image from 'next/image'
import Header from '@/components/admin/index/header'
import TopCards from '@/components/admin/index/topCards'
import BarChart from '../components/admin/index/BarChart';
import RecentOrders from '../components/admin/index/RecentOrders';



export default function Home() {
  return (
    <>
      <Head>
        <title>The Potter's House</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='bg-gray-200 min-h-screen'>
        <Header />
        <TopCards />
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <BarChart />
          <RecentOrders />
        </div>
      </main>
    </>
  )
}
